name: CI

on:
  push:
    branches:
      - "main"
    paths: [ 'hangman-api/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-api/**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build --if-present
      - uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: hangman-api/node_modules/

  tests:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: dependencies
          path: hangman-api/node_modules/
      - name: test
        working-directory: ./hangman-api
        run: npm test
  
  finish:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Hello
        run: echo "Hello, workflow has finised"